### ISSUE TITLE
Crash on macOS 10.11 and older because of os_unfair_lock

### ISSUE THREAD

**Issue by guidedways** [microsoft/plcrashreporter#107] opened 2020-06-25 17:43 UTC
Seeing this:

Dyld Error Message: 
  Symbol not found: _os_unfair_lock_lock 

Desymbolicating says it crashes here:  

+[MSPLCrashReporter initialize]

**Comment by guidedways** [comment] 2020-06-25 17:49
We're using `pod "AppCenter"` how can we switch to an older version of plcrashreporter? This is quite urgent.

**Comment by MatkovIvan** [comment] 2020-06-25 18:15
Hi @guidedways ,

PLCrashReporter is embedded to App Center, so only way to switch to an older version is downgrade App Center SDK.

Could you please share full error report?

**Comment by guidedways** [comment] 2020-06-25 18:17
Thanks - yes I've downgraded. I don't have a full report, this was extracted from a crash report from a user. Everything else in the stack trace is unimportant as it's coming from our app's own process. This is the line where it crashes. I desymbolicated our binary.

**Comment by guidedways** [comment] 2020-06-25 18:17
It's fairly easy to reproduce - build an app using AppCenter and launch it on macOS 10.11, it crashes upon launch.

**Comment by MatkovIvan** [comment] 2020-06-25 18:45
Yeah, it looks like a regression caused by updating deprecated methods for Mac Catalyst (#79). It's weird that the problem is in runtime and everything builds fine even with macOS 10.7 target.
Anyway, thanks for the report, we'll take care about it. Sorry for inconvenience

**Comment by guidedways** [comment] 2020-06-25 18:50
Cheers - I've certainly had my fair share of the same bug. It may simply be building because your're building against the new frameworks, which contain the definition for these supposedly missing methods (on an older macOS version). Either way, a fix would be appreciated - have downgraded for now.

**Comment by MatkovIvan** [comment] 2020-06-30 15:51
Hey!
We've included the fix for this issue to the latest SDK release ([1.7.1](https://github.com/microsoft/plcrashreporter/releases/tag/1.7.1)).
I'm closing it, but please reopen if you some questions or run into this again.

**Closed by MatkovIvan** 2020-06-30 15:51 UTC
Labels: bug
