### ISSUE TITLE
Release 1.6 not compiling for device

### ISSUE THREAD

**Issue by sebids** [microsoft/plcrashreporter#94] opened 2020-05-29 07:37 UTC
I integrated release 1.6 via cocoapods in my project.
When I try to run my app on an iPad Air 2, the compile does not work.

I'm getting the following error from the linker:
`Undefined symbols for architecture arm64:
  "___gxx_personality_v0", referenced from:
      _plcrash_async_objc_isa_pointer in CrashReporter(PLCrashAsyncObjCSection.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Using release 1.5.1 works.

**Comment by lumaxis** [comment] 2020-05-29 08:48
@sebids Thanks for the report! Which Xcode version are you using?

**Comment by MatkovIvan** [comment] 2020-05-29 10:50
Hi @sebids,

The issue is already fixed on `master` - https://github.com/microsoft/plcrashreporter/commit/209ca1f974afc64cf4361afef9339cf198f95614

To make it work with release version just add standard C++ library to the project. It can be done via Xcode UI by adding `libc++.tbd` library or via adding `-lc++` option to `Other Linker Flags`.

Closing the issue because it's already fixed, but feel free to reply here if you still have questions or the problem persists. Thanks.

**Closed by MatkovIvan** 2020-05-29 10:50 UTC
