### ISSUE TITLE
invalid cert on plcrashreporter.org (affects CocoaPods)

### ISSUE THREAD

**Issue by sstadelman** [microsoft/plcrashreporter#54] opened 2020-02-21 23:57 UTC
Affects the CocoaPods spec for v1.2 (already published).  Results in error:

```
Installing PLCrashReporter (1.2.0)

[!] Error installing PLCrashReporter
[!] /usr/bin/curl -f -L -o /var/folders/9x/x_w24rtx1lnc_bf04f4773t80000gn/T/d20200221-38132-1wyl9ha/file.zip https://www.plcrashreporter.org/static/downloads/PLCrashReporter-1.2.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'www.plcrashreporter.org'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by MatkovIvan** [comment] 2020-02-25 07:14
Duplicate of #46
(as well as #48 and #49)

We're working on resolving this issue.

**Closed by MatkovIvan** 2020-02-25 07:14 UTC
