### ISSUE TITLE
Cycle in dependencies between targets 'CrashReporter macOS Framework' and 'CrashReporter macOS'

### ISSUE THREAD

**Issue by MoShenGuo** [microsoft/plcrashreporter#194] opened 2021-06-25 03:15 UTC
你好 运行报错
报错日志:Cycle in dependencies between targets 'CrashReporter macOS Framework' and 'CrashReporter macOS'; building could produce unreliable results.
Cycle path: CrashReporter macOS Framework → CrashReporter macOS → CrashReporter macOS Framework
Cycle details:
Target build order preserved because “Parallelize Build” is off

→ Target 'CrashReporter macOS Framework' has create directory command with output '/Users/bodadmin/Library/Developer/Xcode/DerivedData/CrashReporter-eksjldrdulnvktfokjsnyazxddza/Build/Products/Debug-macosx/CrashReporter.framework/Versions'
→ Target 'CrashReporter macOS': Libtool /Users/bodadmin/Library/Developer/Xcode/DerivedData/CrashReporter-eksjldrdulnvktfokjsnyazxddza/Build/Intermediates.noindex/CrashReporter.build/Debug-macosx/CrashReporter macOS.build/Objects-normal/arm64/Binary/libCrashReporter.a normal arm64
○ Target 'CrashReporter macOS' has compile command with input '/Users/bodadmin/Downloads/plcrashreporter-master/Source/PLCrashReporterNSError.m'
→ Target 'CrashReporter macOS Framework' has write command with output /Users/bodadmin/Library/Developer/Xcode/DerivedData/CrashReporter-eksjldrdulnvktfokjsnyazxddza/Build/Intermediates.noindex/CrashReporter.build/Debug-macosx/CrashReporter macOS Framework.build/module.modulemap
![image](https://user-images.githubusercontent.com/21171688/123364221-a5548800-d5a6-11eb-845f-524b16211697.png)
还望指教

**Comment by russelarms** [comment] 2021-06-25 08:42
Hi @MoShenGuo, thanks for reaching out! I could reproduce the issue.
Repro steps:
1. build "CrashReporter macOS"
2. build "CrashReporter macOS Framework"
3. build "CrashReporter"
4. build "CrashReporter macOS Framework"

@MoShenGuo what Xcode version do you use?

The current workaround is to clean cache:
`Product > Clean Build Folder`.

**Comment by MatkovIvan** [comment] 2021-06-25 09:01
@russelarms It's most likely due to implicit dependencies finding on new Xcode versions (we faced with this Xcode bug before). Make sure that targets have unchecked "Find Implicit Dependencies" setting in build scheme.

**Comment by AnastasiaKubova** [comment] 2021-06-30 06:32
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by richardgroves** [comment] 2021-07-23 12:14
I'm seeing this problem with the latest code and all 'Find Implicit Dependencies' unchecked for every scheme. Using XCode 12.5.1. Same scenario as above: Do one successful build and the next one will fail with an error. Have to clean + full rebuild to work around, which isn't great.

```
Cycle in dependencies between targets 'CrashReporter iOS Framework' and 'CrashReporter iOS'; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
Cycle path: CrashReporter iOS Framework → CrashReporter iOS → CrashReporter iOS Framework
Cycle details:
→ Target 'CrashReporter iOS Framework': Libtool /Users/richard/Library/Developer/Xcode/DerivedData/CrashReporter-duzgqhmryouqdqemdmlrxtbbntwu/Build/Products/Debug-iphonesimulator/CrashReporter.framework/CrashReporter normal
○ Target 'CrashReporter iOS Framework': MasterObjectLink /Users/richard/Library/Developer/Xcode/DerivedData/CrashReporter-duzgqhmryouqdqemdmlrxtbbntwu/Build/Intermediates.noindex/CrashReporter.build/Debug-iphonesimulator/CrashReporter iOS Framework.build/Objects-normal/CrashReporter-x86_64-master.o
○ Target 'CrashReporter iOS Framework' has compile command with input '/Users/richard/Code/Tools and Components/PLCrashReporter/Source/CrashReporterFramework.m'
○ Target 'CrashReporter iOS Framework' has process command with input '/Users/richard/Code/Tools and Components/PLCrashReporter/Source/PLCrashNamespace.h'
○ Target 'CrashReporter iOS Framework' has write command with output /Users/richard/Library/Developer/Xcode/DerivedData/CrashReporter-duzgqhmryouqdqemdmlrxtbbntwu/Build/Intermediates.noindex/CrashReporter.build/Debug-iphonesimulator/CrashReporter iOS Framework.build/module.modulemap
○ Target 'CrashReporter iOS Framework' has target dependency on Target 'CrashReporter iOS'
→ Target 'CrashReporter iOS' has compile command with input '/Users/richard/Code/Tools and Components/PLCrashReporter/Source/CrashReporter.m'
```

**Comment by AnastasiaKubova** [comment] 2021-07-26 08:00
Thanks for mention it. I will label this issue as a bug.

**Comment by aleksandr-dorofeev** [comment] 2021-08-10 11:58
Hi @MoShenGuo and @richardgroves Please, try to use this branch [v-adorofeev/fix-cycle-in-dependencies](https://github.com/microsoft/plcrashreporter/tree/v-adorofeev/fix-cycle-in-dependencies) and check if it works for you.

**Comment by richardgroves** [comment] 2021-08-10 13:42
@aleksandr-dorofeev Looks good to me - was able to build the iOS version a second time without any errors.

**Comment by DmitriyKirakosyan** [comment] 2021-08-11 14:27
Actually, this fix doesn't handle all cases and the error `Cycle in dependencies` can still happen when switching between targets in PLCrashReporter project. However, I believe it is more an Xcode bug.
The PR looks OK though, and all CI checks are passed. I'll do a bit more of manual testing and merge the PR.

**Comment by DmitriyKirakosyan** [comment] 2021-08-12 13:43
PR is merged.
I'm closing this issue, but feel free to reopen if you face the issue again.

**Closed by DmitriyKirakosyan** 2021-08-12 13:43 UTC
Labels: bug
