### ISSUE TITLE
Library is not able to load pending crash report and throwing an error Domain=PLCrashReporterErrorDomain Code=2

### ISSUE THREAD

**Issue by dhawal-aeq** [microsoft/plcrashreporter#305] opened 2024-04-09 18:38 UTC
### **Description**

We have integrated CrashReporter into our project and trying to capture crash reports but somehow it's not able to load report and throwing below error:
**failed to load and parse with error: Error Domain=PLCrashReporterErrorDomain Code=2 "An unknown error occured decoding the crash report" UserInfo={NSLocalizedDescription=An unknown error occured decoding the crash report}**

However, when we use the same configuration with sample app then it works fine, seems like something in the project which is causing an issue but we are not able to figure out.

### **Repro Steps**

Here is the code that we have added in the didFinishLaunching to verify the crashes:

          let config = PLCrashReporterConfig(signalHandlerType: .mach, symbolicationStrategy: .all)

          guard let crashReporter = PLCrashReporter(configuration: config) else {
            print("Could not create an instance of PLCrashReporter")
            return true
          }

        // Enable the Crash Reporter.
          do {
            try crashReporter.enableAndReturnError()
          } catch let error {
            print("Warning: Could not enable crash reporter: \(error)")
          }

        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
            fatalError("Crashed")
        }
        
        // Try loading the crash report.
          if crashReporter.hasPendingCrashReport() {
            do {
              let data = try crashReporter.loadPendingCrashReportDataAndReturnError()
                print("CrashReporter: Loaded data")
              // Retrieving crash reporter data.
              let report = try PLCrashReport(data: data)
                print("CrashReporter: Loaded report")
              // We could send the report from here, but we'll just print out some debugging info instead.
              if let text = PLCrashReportTextFormatter.stringValue(for: report, with: PLCrashReportTextFormatiOS) {
                print(text)
              } else {
                print("CrashReporter: can't convert report to text")
              }
            } catch let error {
              print("CrashReporter: failed to load and parse with error: \(error)")
            }
          } else {
              print("CrashReporter: No pending reports")
          }

### **Details**

1. Which SDK version are you using? Latest
2. Which OS version did you experience the issue on? 17.2
3. Which CocoaPods/Carthage/Xcode version are you using? CocoaPods
4. What device version did you see this error on? Were you using an emulator or a physical device? Simulator
5. What language are you using?
    - [ ] Objective C
    - [X] Swift
6. What third party libraries are you using?
```
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/Crashlytics'
pod 'Introspect'
pod 'XMLCoder', '~> 0.14.0'
pod 'Factory', '2.1.5'
pod 'DatadogCore'
pod 'DatadogRUM'
pod 'DatadogSessionReplay'
pod 'DatadogCrashReporting'
pod` 'SwiftLint'
```

and some private third party libraries from Backbase

For your information, we have also tried to disable Firebase in case it is creating an issue but same error.

Please find attachments for crashReport data that we gathered from APP's cache folder, we believe this is the place where CrashReport is capturing the crashes and also .ips file that the system generated for the crash.
[com.plausiblelabs.crashreporter.data.zip]
[Ent dev2-2024-04-09-110918.ips.zip](https://github.com/microsoft/plcrashreporter/files/14922712/Ent.dev2-2024-04-09-110918.ips.zip)
(https://github.com/microsoft/plcrashreporter/files/14922709/com.plausiblelabs.crashreporter.data.zip)

**Comment by grigorye** [comment] 2024-04-16 14:29
I do believe that it may be the same issue that we encountered on our side. Basically, in our case it was narrowed-down to the fact that the crash report generated exceeded the limit hardcoded in the library. You can check that by trying to look up for the saved crash report in the app container and checking its size. If it's 262144 (that's 256KB), then it's probably the same issue.

The workaround is implemented in #308 (increasing the limit from 256KB to 1MB).

After lifting the limit, in our case the real size of the crash report generated was 289858 bytes.

**Comment by DmitriyKirakosyan** [comment] 2024-04-17 13:15
Hi @dhawal-aeq, could you please check if you are experiencing the same issue that @grigorye has described?

@grigorye, thanks for your contribution! How frequently does such a big crash occur? Is it a constant issue or does it occur only under specific circumstances? You've increased the limit to 1MB. Is this amount necessary? Perhaps 512KB might suffice. The limit is intended to prevent excessive disk usage, see [this link](https://github.com/microsoft/plcrashreporter/blob/cf13382a1b2dcb09416c416ee293cd01536de596/Source/PLCrashAsync.c#L442).

Have you tested your changes by integrating the patched version into your app?  How do you integrate PLCRashReporter? SPM, Pods?

**Comment by grigorye** [comment] 2024-04-17 16:27
> @grigorye, thanks for your contribution! How frequently does such a big crash occur? Is it a constant issue or does it occur only under specific circumstances? You've increased the limit to 1MB. Is this amount necessary? Perhaps 512KB might suffice. The limit is intended to prevent excessive disk usage, see [this link](https://github.com/microsoft/plcrashreporter/blob/cf13382a1b2dcb09416c416ee293cd01536de596/Source/PLCrashAsync.c#L442).

Well, it's 100% reproducible in our case, with nothing but a typical setup for our UI implementation.

> Have you tested your changes by integrating the patched version into your app? 

Yes.

> How do you integrate PLCRashReporter? SPM, Pods?

We're in fact integrating it implicitly as part of [DatadogCrashReporting](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogSDKCrashReporting.podspec), via CocoaPods. To integrate the patched version (until the official version is released here), we (temporarily) employed a [fork](https://github.com/grigorye/plcrashreporter/tree/mp) ([preview](https://github.com/microsoft/plcrashreporter/compare/1.11.1...grigorye:plcrashreporter:mp) of the changes) (beware that it branches of 1.11.1 (the last officially released version)).

OTOH, as far as I can see, the fix has been already merged and folks are [preparing](https://github.com/microsoft/plcrashreporter/commit/db45746934f069ec41b8a80c67292a1f92228e6d) 1.11.2, so I'm looking forward to the new official version that addresses the issue.

**Comment by grigorye** [comment] 2024-04-17 16:36
>Is this amount necessary? Perhaps 512KB might suffice. The limit is intended to prevent excessive disk usage, see [this link](https://github.com/microsoft/plcrashreporter/blob/cf13382a1b2dcb09416c416ee293cd01536de596/Source/PLCrashAsync.c#L442).

Tbh, I'm not sure I understand the rationale behind this limit to the end, but at quick glance it looks like addressing "internal safety" issue vs something specific. From that perspective the difference between 1M or 512K sounds irrelevant to me - if it lands in that kind of situation, whether it stops at 1M or 512K does not matter?

Also, I followed the rationale that they had in the documentation with the current limit: 256K was used when the largest observed crash report was around 97K, that is 2.5x larger than the observation. Here we have the case with 290K crash report that we observed in real life, so 512K would be less than 2x, hence my proposal was to use 1M, just to be on the safe side of the things.

**Comment by dhawal-aeq** [comment] 2024-04-17 17:10
@DmitriyKirakosyan Seems like this is the same issue that @grigorye is having, I can see my crash report is 262KB and that explains why CrashReporter is not able to load the crash report. I agree with @gimsvc we should have limit set to 2.5x larger than observation as there might be lot of cases where we could end up in big report.

Do you have any timeline for the release of 1.11.2

**Comment by DmitriyKirakosyan** [comment] 2024-06-10 07:31
The fix was released, so I'm closing this issue.

**Closed by DmitriyKirakosyan** 2024-06-10 07:31 UTC
Labels: support
