### ISSUE TITLE
Missing "Last Exception Backtrace" section

### ISSUE THREAD

**Issue by chandakvishal** [microsoft/plcrashreporter#170] opened 2021-03-09 05:30 UTC
Recently we are seeing crashes that are lacking the section "Last Exception Backtrace". These crashes are the top crashes for the most recent version we released. Using Xcode Organizer, we can see that the top crashes reported by Apple do indeed have very similar stack traces for the crashed threads, but they also have the last exception backtrace.

**Comment by MatkovIvan** [comment] 2021-03-09 06:40
Hi @chandakvishal,
Could you please provide reproduction sample, versions, etc? Just use issue template for problem report.

Also, please note that there is some limitations in in-process crash reporting by design.
Thanks.

**Comment by Jamminroot** [comment] 2021-03-12 09:12
Hey @chandakvishal, we haven't heard from you for a while, is the issue still relevant?

**Comment by chandakvishal** [comment] 2021-03-15 11:25
Hey @MatkovIvan @Jamminroot This is still relevant. Sorry for the delay in response.

Crash Captured by XCode:
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0
```

Crash Captured by PLCrashReporter:
```
Exception Type:  SIGABRT
Exception Codes: #0 at 0x1c7dfa414
Crashed Thread:  0
```
Unfortunately I do not have the steps to reproduce it but this is happening primarily when we initialize PLCrashReporter as early as possible in the launch cycle. This is most likely due to a crash during the initialization of the application.

Example `Last Exception Backtrace` lines missing in PLCrashReporter report but captured by XCode:
```
Last Exception Backtrace:
0   CoreFoundation                	0x19cad8878 __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1b102ec50 objc_exception_throw + 60 (objc-exception.mm:565)
2   UIKitCore                     	0x19f60a6cc +[UIStoryboard storyboardWithName:bundle:] + 732 (UIStoryboard.m:0)
3   ApplicationName                     0x10550f97c @nonobjc UIStoryboard.__allocating_init(name:bundle:) + 64 (<compiler-generated>:0)
....
....
....
Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001c99d7414 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001e5eefb40 pthread_kill + 272 (pthread.c:1388)
2   libsystem_c.dylib             	0x00000001a5dfcb74 abort + 104 (abort.c:110)
3   libc++abi.dylib               	0x00000001b1134cf8 abort_message + 132 (abort_message.cpp:76)
4   libc++abi.dylib               	0x00000001b1125e4c demangling_terminate_handler() + 308 (cxa_default_handlers.cpp:67)
```

**Comment by MatkovIvan** [comment] 2021-03-16 08:53
It's hard to identify the exact reason based on this information. It can be limitation of in-process crash reporting - if it's a crash during initialization - it's kind of expected (known limitation)

**Comment by russelarms** [comment] 2021-03-22 09:34
We're closing this one until there's more information about the problem.

**Closed by russelarms** 2021-03-22 09:34 UTC
Labels: need more info
