### ISSUE TITLE
SSL certificate on https://www.plcrashreporter.org/

### ISSUE THREAD

**Issue by ramil-k** [microsoft/plcrashreporter#49] opened 2020-01-17 09:25 UTC
Hi, I've encountered problem that I can't load library (1.2.0 if it's important) due to some SSL problems. Also, browser is showing warnings when I'm trying open website

**Comment by ilyashumihin** [comment] 2020-01-17 10:03
Hi, @ramil-k!
Thanks for getting in touch!

This issue has already been discussed in these topics - duplicate of #46,  #48

**Closed by ilyashumihin** 2020-01-17 10:03 UTC
