### ISSUE TITLE
PLCrashReporter breaks background app relaunch on iOS 14

### ISSUE THREAD

**Issue by mh-dmclean** [microsoft/plcrashreporter#138] opened 2020-10-05 19:41 UTC
### **Description**

Enabling the PLCrashReporter framework causes the app to no longer be able to relaunch in the background on iOS 14

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Have an app with the legacy-voip entitlement
2. Use PLCrashReporter in the app (directly or transitively through AppCenter)
3. Start the app
4. Crash the App

Expected: When the app crashes, it is relaunched in the background without user intervention

Actual: The app does not relaunch in the background

### **Details**

1. Which SDK version are you using?
    1.7.2
2. Which OS version did you experience the issue on?
    iOS 14.0+
3. Which CocoaPods/Carthage/Xcode version are you using?
    CocoaPods 1.9.1
    Xcode 12.GM.seed/Xcode 12.2 Beta/Xcode 11.7
4. What device version did you see this error on? Were you using an emulator or a physical device?
    Physical iOS devices (model doesn't seem to be a factor)
5. What language are you using?
    - [X] Objective C
    - [X] Swift
6. What third party libraries are you using?
- CocoaLumberjack
- KissXML
- XMPPFramework
- RealmSwift
- PLCrashReporter

**Comment by vvechkanov** [comment] 2020-10-07 20:16
Hi!

We are looking into this issue. To help us better understand what is going on, could you please send us logs, after the app crash. This will help us understand better what is going on with your application when it is crashing and what can block restarting.

**Comment by russelarms** [comment] 2020-10-13 09:36
Hi @mh-dmclean, could you provide a demo project for that problem, because we couldn't reproduce it locally?

**Comment by AnastasiaKubova** [comment] 2020-10-26 06:39
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Closed by AnastasiaKubova** 2020-10-26 06:39 UTC
Labels: support
