### ISSUE TITLE
plcrashreporter1.7 crash on iOS9

### ISSUE THREAD

**Issue by iwarhuang** [microsoft/plcrashreporter#118] opened 2020-07-13 06:28 UTC
### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. init the plcrashrepoter then will be crash on plcrash::PL_::async::async_list<plcrash_async_image*>::nasync_append

??? | 0x000000016fd9b460 + 0
-- | --
1 ??? | 0x0000000180dcac8a + 0
2 ??? | 0x000000019aa13b60 + 0
3 libdyld.dylib | dyld_stub_binder + 60
4 MyApp | plcrash::PL_::async::async_list<plcrash_async_image*>::nasync_append(plcrash_async_image*) + 24
5 MyApp| image_add_callback + 52
6 ??? | 0x0000000180dcac8a + 0
7 libdyld.dylib | _dyld_register_func_for_add_image + 76
8 MyApp | +[PLCrashReporter initialize] + 108

### **Details**

1. Which SDK version are you using?
1.7
2. Which OS version did you experience the issue on?
iOS9
3. Which CocoaPods/Carthage/Xcode version are you using?
1.8.4
4. What device version did you see this error on? Were you using an emulator or a physical device?
iphone6s
5. What language are you using?
 Objective C

6. What third party libraries are you using?

**Comment by MatkovIvan** [comment] 2020-07-13 06:38
Hi @iwarhuang,

It's a duplicate of #107. This issue has been already fixed and the hotfix has been released. Please update to [1.7.1](https://github.com/microsoft/plcrashreporter/releases/tag/1.7.1).

**Closed by MatkovIvan** 2020-07-13 06:38 UTC
Labels: support
