### ISSUE TITLE
Lack of arm64-simulator slice via Cocoapods

### ISSUE THREAD

**Issue by buranmert** [microsoft/plcrashreporter#203] opened 2021-08-13 10:30 UTC
### **Description**

[`PLCrashReporter.podspec` ships a vendored framework named `CrashReporter.framework`](https://github.com/microsoft/plcrashreporter/blob/master/PLCrashReporter.podspec#L15) and it lacks `arm64-iphonesimulator` slice as expected.

#### Problem 1

We use `PLCrashReporter` as a dependency in our [`DatadogSDKCrashReporting` pod](https://github.com/DataDog/dd-sdk-ios/blob/master/DatadogSDKCrashReporting.podspec#L23)
When we `pod trunk push DatadogSDKCrashReporting.podspec`, it fails as explained below in **Repro Steps** section.
It also fails with the same error when I `pod spec lint` with `PLCrashReporter.podspec`.

#### Problem 2

Apple M1 owner developers can't be running their projects in their simulators if they depend on `PLCrashReporter`.
(I haven't tested that first-hand, so feel free to correct me if I'm wrong.)

### **Repro Steps**

1. run `pod spec lint --use-libraries --verbose --platforms=ios PLCrashReporter.podspec`

#### Expected result
`PLCrashReporter.podspec` passes validation.

#### Actual result
Validation fails with the following last lines:
```
The following build commands failed:
  Ld {DerivedData}/App-foo/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/Binary/App normal arm64
```

### Proposed solution

I'm guessing that if `PLCrashReporter.podspec` shipped [PLCrashReporter-XCFramework-1.9.0.zip](https://github.com/microsoft/plcrashreporter/releases/download/1.9.0/PLCrashReporter-XCFramework-1.9.0.zip) as `vendored_frameworks` instead of [PLCrashReporter-1.9.0.zip](https://github.com/microsoft/plcrashreporter/releases/download/1.9.0/PLCrashReporter-1.9.0.zip), this issue could be resolved.

### **Details**

1. Which SDK version are you using? **Tried both `1.9.0` and `1.8.1`**
2. Which OS version did you experience the issue on? **Any OS, the issue must have started with Xcode 12**
3. Which CocoaPods/Carthage/Xcode version are you using? **`Cocoapods 1.10.1`**
4. What device version did you see this error on? Were you using an emulator or a physical device? **Compilation issue**
5. What language are you using?
    - [x] Objective C
    - [x] Swift
6. What third party libraries are you using? **None**

**Comment by buranmert** [comment] 2021-08-13 10:32
I'm also wondering how you push `PLCrashReporter.podspec` to cocoapods: `pod trunk push` must be failing as `pod spec lint` fails, are you pushing it directly to `trunk` without using Cocoapods CLI?

**Comment by DmitriyKirakosyan** [comment] 2021-08-13 15:25
Hi @buranmert 

Thank you for bringing this issue to our attention!

Unfortunately, we can't ship `.xcframework` with Cocoapods, because PLCrashReporter has static and dynamic libraries in one framework and this behavior is not currently supported by Cocoapods (See [CocoaPods + mixed (static+dynamic for mac) XCFramework issue](https://github.com/CocoaPods/CocoaPods/issues/10262)).

We are using `pod trunk push` with Xcode 11.7 on our CI and it works fine.
I tried to run it locally with Xcode 12 and it fails, indeed.

> Problem 2
> Apple M1 owner developers can't be running their projects in their simulators if they depend on PLCrashReporter.
> (I haven't tested that first-hand, so feel free to correct me if I'm wrong.)
> 

You are right, it doesn't build for simulator on M1, just verified it. I'll investigate if we can fix these issues with `pod spec lint` and building for simulator on M1.

**Comment by buranmert** [comment] 2021-08-13 15:55
thanks for the quick reply @DmitriyKirakosyan !
please let me know if i can do anything to fix the issue

and i was wondering if it could work to put 2 `.xcframework`s within the zip file?
```
PLCrashReporter-XCFramework-#{spec.version}.zip
|
|-- CrashReport-dynamic.xcframework (contains macOS frameworks)
|-- CrashReport-static.xcframework (contains iOS & tvOS frameworks)
```
then the podspec would be:
```
spec.osx.vendored_frameworks = "CrashReport-dynamic.xcframework"
spec.ios.vendored_frameworks = "CrashReport-static.xcframework"
spec.tvos.vendored_frameworks = "CrashReport-static.xcframework"
```

**Comment by DmitriyKirakosyan** [comment] 2021-08-13 17:07
Actually, we already thought about providing a separate xcframework with only static libs for the Cocoapods integration. May be it is time to prioritize it.

Your suggestion looks interesting! I'm wondering if we can avoid increasing size of the zip file following this approach.
It would be great, if you can test such approach and let us know if it actually works.

**Comment by MatkovIvan** [comment] 2021-08-15 18:53
Hi @buranmert,
I just wanted to clarify the thing about `pod spec lint`. From [Deploying your Library](https://guides.cocoapods.org/making/using-pod-lib-create.html#deploying-your-library):
> First you should check if the Podspec lints correctly, as you can't deploy with errors. This can be done with two methods, `pod lib lint` and `pod spec lint`. The difference between them is that `pod lib lint` does not access the network, whereas `pod spec lint` checks the external repo and associated tag.

PLCR uses `pod lib lint` for prepared zip archive that you can find in releases. As you see `pod spec lint` is just not used and it's not an issue in this case.

**Comment by DmitriyKirakosyan** [comment] 2021-08-16 23:07
I experimented a bit with different versions of Xcode and here are the results:
- `pod spec lint` finishes with success on Xcode versions <= 12.3. Starting from 12.4 it fails because it tries to build for m1 simulator and fails with the error above.
- `pod lib lint` fails on all versions of Xcode starting from 11.7 (didn't check lower versions) with error `[iOS] file patterns: The 'vendored_frameworks' pattern did not match any file.`.

I think the only option to solve the issue is to distribute `xcframework` via Cocoapods. We will discuss it within the team and prioritise when we have capacity for this work.

@buranmert, I'll keep you updated.

**Comment by buranmert** [comment] 2021-08-18 09:10
thanks for your positive response!

just to be clear about my proposal,
i downloaded [`PLCrashReporter-XCFramework-1.9.0.zip`](https://github.com/microsoft/plcrashreporter/releases/download/1.9.0/PLCrashReporter-XCFramework-1.9.0.zip) from your release assets, moved `macos` parts out to another `xcframework` as seen below:

<img width="295" alt="plcr-issue-demo" src="https://user-images.githubusercontent.com/1417500/129868068-55830165-4d09-4874-aa5e-84e6b47e5ad0.png">

as there is no duplicates, i hope overall file size would not be an issue.
then the last step is changing [the podspec](https://github.com/microsoft/plcrashreporter/blob/1.9.0/PLCrashReporter.podspec) to:
```ruby
Pod::Spec.new do |spec|
  spec.name        = 'PLCrashReporter'
  ...
  spec.source      = { :http     => "https://github.com/microsoft/plcrashreporter/releases/download/#{spec.version}/PLCrashReporter-cocoapods-#{spec.version}.zip",
                       :flatten  => true }
  spec.osx.vendored_frameworks  = "CrashReporter-macOS.xcframework"
  spec.ios.vendored_frameworks  = "CrashReporter.xcframework"
  spec.tvos.vendored_frameworks = "CrashReporter.xcframework"
end
```

i will see if i can find some time to try that before going on vacation next week :)

**Comment by DmitriyKirakosyan** [comment] 2021-09-13 19:16
Hi @buranmert 

You can now integrate XCFramework via Cocoapods.
Closing the issue.

**Closed by DmitriyKirakosyan** 2021-09-13 19:16 UTC
Labels: support
