### ISSUE TITLE
Xcode 14 Carthage build errors

### ISSUE THREAD

**Issue by pepas-everly** [microsoft/plcrashreporter#261] opened 2022-09-12 21:59 UTC
Under Xcode 14, `armv7s` is no longer supported, and `11.0` is the minimum deployment target.

```
.../CrashReporter.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99.
```

```
error: The armv7s architecture is deprecated. You should update your ARCHS build setting to remove the armv7s architecture.
```

Please remove this architecture and bump the deployment target.

While waiting for these fixes, existing Carthage users can use the following work-around:

```
carthage update --no-build

# Fix CrashReporter by bumping its deployment target, removing the armv7s arch, and fixing the PLCR_LOG macro.
# See https://github.com/microsoft/plcrashreporter/issues/261
cd Carthage/Checkouts/plcrashreporter
    sed -I '' 's/IPHONEOS_DEPLOYMENT_TARGET = 9.0;/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/'  CrashReporter.xcodeproj/project.pbxproj
    sed -I '' '/armv7s,/d' CrashReporter.xcodeproj/project.pbxproj
    patch -p1 << 'EOF'
diff -urN plcrashreporter/Source/PLCrashMacros.h plcrashreporter2/Source/PLCrashMacros.h
--- plcrashreporter/Source/PLCrashMacros.h	2022-04-01 12:27:34.652198389 -0500
+++ plcrashreporter2/Source/PLCrashMacros.h	2022-09-12 17:12:23.051245996 -0500
@@ -141,13 +141,8 @@
 #endif /* PLCR_PRIVATE */
 
 #ifdef PLCR_PRIVATE
-#  if TARGET_OS_MACCATALYST
-#    include <os/log.h>
-#    define PLCR_LOG(msg, args...) os_log(OS_LOG_DEFAULT, "[PLCrashReporter] "  msg, ## args)
-#  else
-#    include <asl.h>
-#    define PLCR_LOG(msg, args...) asl_log(NULL, NULL, ASL_LEVEL_INFO, "[PLCrashReporter] " msg, ## args)
-#  endif /* TARGET_OS_MACCATALYST */
+#include <os/log.h>
+#define PLCR_LOG(msg, args...) os_log(OS_LOG_DEFAULT, "[PLCrashReporter] "  msg, ## args)
 #endif /* PLCR_PRIVATE */
 
 #endif /* PLCRASH_CONSTANTS_H */
EOF

cd - > /dev/null

carthage build --use-xcframeworks --platform iOS --no-use-binaries --cache-builds
```

**Comment by pepas-everly** [comment] 2022-09-12 22:00
UPDATE: ah, after fixing the arch and deployment target, there are some additional build errors.  All of them appear to be issues with `PLCR_LOG`.

```
.../Carthage/Checkouts/plcrashreporter/Source/PLCrashReporter.m:335:9: error: 'asl_log' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3) [-Werror,-Wdeprecated-declarations]
        PLCR_LOG("%s: dladdr(%p, ...) failed", __FUNCTION__, mh);
```

**Comment by pepas-everly** [comment] 2022-09-12 22:11
It appears there is already an implementation of `PLCR_LOG` which uses `os_log`:

```
#ifdef PLCR_PRIVATE
#  if TARGET_OS_MACCATALYST
#    include <os/log.h>
#    define PLCR_LOG(msg, args...) os_log(OS_LOG_DEFAULT, "[PLCrashReporter] "  msg, ## args)
#  else
#    include <asl.h>
#    define PLCR_LOG(msg, args...) asl_log(NULL, NULL, ASL_LEVEL_INFO, "[PLCrashReporter] " msg, ## args)
#  endif /* TARGET_OS_MACCATALYST */
#endif /* PLCR_PRIVATE */
```

So probably we can just remove the `#  if TARGET_OS_MACCATALYST` and always use the `os_log` implementation?

**Comment by aleksandr-dorofeev** [comment] 2022-09-13 12:39
Hi @pepas-everly 
Thank you for getting in touch with us and reporting this issue and for the proposed solution!
I filed a bug on our board and we will fix it according to our priority queue.
I'll be back with an update as we fix the bug and test the changes.

**Comment by wangjiejacques** [comment] 2022-10-28 12:29
Hi @DmitriyKirakosyan , do you have a plan about the next release?

**Comment by MikhailSuendukov** [comment] 2022-10-31 11:26
Hi @wangjiejacques, we have already released, so I'm closing this issue. Feel free to reopen it if the problem is still present.

**Closed by MikhailSuendukov** 2022-10-31 11:26 UTC
Labels: support, next-release

**Comment by ohayon** [comment] 2023-04-13 17:52
Hi @MikhailSuendukov - I am still hitting this on archive builds only. Is there a workaround for this?

**Comment by DmitriyKirakosyan** [comment] 2023-04-20 09:25
Hi @ohayon , note that latest version of PLCRashReporter supports iOS 11 or newer, so make sure you target iOS 11 or newer.
