### ISSUE TITLE
Fix apple M1 chip new machine Crash。

### ISSUE THREAD

**Issue by dander521** [microsoft/plcrashreporter#168] opened 2021-02-18 09:48 UTC
Fix apple M1 chip new machine Crash。

**Comment by MatkovIvan** [comment] 2021-02-18 13:32
Hi @dander521,

The library was tested on arm macs and we didn't find problems. Please fill issue template properly, describe reproduction steps or share sample project.

Closing because of invalid description.

**Closed by MatkovIvan** 2021-02-18 13:32 UTC
